import "./globals.css";
import { maliFont } from "./(website)/Components/Utils/font";

export const metadata = {
  title: "TruBuddies",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${maliFont.className}`}>{children}</body>
    </html>
  );
}
