import "./globals.css";
import { maliFont } from "./(website)/Components/Utils/font";
import State from "./Context/State";
import Head from "next/head";

export const metadata = {
  title: "TruBuddies",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <State>
        <Head>
          <script
            async
            src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3501133654906163"
            crossorigin="anonymous"
          ></script>
          <meta
            name="google-adsense-account"
            content="ca-pub-3501133654906163"
          />
        </Head>
        <body className={`${maliFont.className}`}>{children}</body>
      </State>
    </html>
  );
}
